#!/bin/fish
sudo rm -rf ./ghostty ./dunst ./fish ./hypr ./nvim ./ranger ./rofi ./solaar ./tmux ./waybar ./wallust ./wezterm ./xkb
cp -r ~/.config/ghostty ~/.config/dunst ~/.config/fish ~/.config/hypr ~/.config/nvim ~/.config/ranger ~/.config/rofi ~/.config/solaar ~/.config/tmux ~/.config/waybar ~/.config/wallust ~/.config/wezterm ~/.config/xkb -t ./
sudo chmod -R 777 ./ghostty ./dunst ./fish ./hypr ./nvim ./ranger ./rofi ./solaar ./tmux ./waybar ./wallust ./wezterm ./xkb
sudo chown -R felipe ./ghostty ./dunst ./fish ./hypr ./nvim ./ranger ./rofi ./solaar ./tmux ./waybar ./wallust ./wezterm ./xkb
