-- Hyprland colors — auto-generated by wallust, do not edit manually
-- Required by ~/.config/hypr/hyprland.lua

hl.config({
    general = {
        col = {
            active_border = {
                colors = { "rgb({{color4 | lighten(0.2) | strip}})", "rgb({{color2 | strip}})" },
                angle = 45,
            },
            inactive_border = "rgba({{background | lighten(0.1) | strip}}66)",
        },
    },
})
