# zsh colors — auto-generated by wallust, do not edit manually

typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[command]='fg={{color4}}'
ZSH_HIGHLIGHT_STYLES[builtin]='fg={{color4}}'
ZSH_HIGHLIGHT_STYLES[alias]='fg={{color4}}'
ZSH_HIGHLIGHT_STYLES[function]='fg={{color4}}'
ZSH_HIGHLIGHT_STYLES[precommand]='fg={{color4}},underline'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg={{color1}}'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg={{color5}}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg={{color3}}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg={{color3}}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg={{color3}}'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg={{color6}}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg={{color6}}'
ZSH_HIGHLIGHT_STYLES[comment]='fg={{color8}}'
ZSH_HIGHLIGHT_STYLES[path]='fg={{foreground}},underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg={{color2}}'
ZSH_HIGHLIGHT_STYLES[assign]='fg={{foreground}}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg={{color5}}'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg={{color6}}'

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg={{color8}}'
