-- Hyprland Lua config (Hyprland >= 0.55)
-- https://wiki.hypr.land/Configuring/Start/
--
-- kingsport: a browser-and-WoW box for a Windows user. The point of a tiling
-- WM here is not tiling; it's that fullscreen games get a real fullscreen and
-- nothing (no panel, no compositor effect) fights them. Keep the keybinds few
-- and mouse-first: waybar has a start button, Super alone opens the launcher.

------------------
---- MONITORS ----
------------------

-- Auto-detect. Replace with the real output once the machine exists, e.g.
-- hl.monitor({ output = "DP-1", mode = "2560x1440@165", position = "0x0", scale = 1 })
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "ghostty"
local browser     = "zen-browser"
local fileManager = "dolphin"
local launcher    = "rofi -show drun"


------------------
---- COLORS ------
------------------

-- Border colors are generated by wallust into hyprland-colors.lua
require("hyprland-colors")


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("HYPRCURSOR_SIZE", "28")
hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("XCURSOR_SIZE", "28")
hl.env("XCURSOR_THEME", "BreezeX-RosePine-Linux")
hl.env("GTK_THEME", "Adwaita:dark")
hl.env("GDK_CORE_DEVICE_EVENTS", "1")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    input = {
        -- TODO: her layout. "us" with intl variant, or "br" for ABNT2.
        kb_layout  = "us",
        kb_variant = "",
        kb_options = "",

        follow_mouse = 1,
        sensitivity  = 0,

        touchpad = {
            natural_scroll = false,
        },
    },

    general = {
        gaps_in     = 6,
        gaps_out    = 16,
        border_size = 3,
        -- Border colors come from hyprland-colors.lua (wallust)

        layout = "dwindle",

        -- Games get tearing per window via the `immediate` rule below;
        -- this only permits it globally.
        allow_tearing = true,
    },

    decoration = {
        rounding = 12,

        blur = {
            enabled           = true,
            new_optimizations = true,
            size              = 8,
            passes            = 2,
            special           = true,
        },

        shadow = {
            enabled      = true,
            range        = 12,
            render_power = 3,
            color        = 0x66000000,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
        smart_split    = true,
    },

    misc = {
        force_default_wallpaper = 0,
        -- VRR only for fullscreen windows (games); desktop stays fixed-rate.
        vrr = 2,
    },
})

hl.curve("cozy", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })

hl.animation({ leaf = "windows",    enabled = true, speed = 6,  bezier = "cozy" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 6,  bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fade",       enabled = true, speed = 6,  bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5,  bezier = "default" })


----------------------
---- WINDOW RULES ----
----------------------

-- Everything Steam launches (Proton, native) gets real fullscreen, tearing,
-- and keeps the screen awake. WoW under Proton is a steam_app_* class too.
hl.window_rule({
    name  = "steam-games",
    match = { class = "^(steam_app_.*)$" },
    fullscreen   = true,
    immediate    = true,
    idle_inhibit = "always",
})

-- WoW outside Steam (Battle.net via Lutris/Wine). Wine reports the exe name.
hl.window_rule({
    name  = "wow-wine",
    match = { class = "^(wow\\.exe|Wow\\.exe|WowClassic\\.exe)$" },
    fullscreen   = true,
    immediate    = true,
    idle_inhibit = "always",
})

-- Launchers float: Battle.net, Steam's small windows, Lutris.
hl.window_rule({
    name  = "launchers-float",
    match = { class = "^(battle\\.net\\.exe|Battle\\.net|lutris|net\\.lutris\\.Lutris)$" },
    float = true,
})
hl.window_rule({
    name  = "steam-dialogs-float",
    match = { class = "^(steam)$", title = "^(Friends List|Steam Settings|Screenshot Manager|Special Offers)$" },
    float = true,
})

-- Browser picture-in-picture stays on top, floating.
hl.window_rule({
    name  = "pip",
    match = { title = "^(Picture-in-Picture|Picture in picture)$" },
    float = true,
    pin   = true,
})

-- Ignore maximize requests; the layout owns window size.
hl.window_rule({
    name  = "suppress-maximize",
    match = { class = ".*" },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland (from the default config).
hl.window_rule({
    name  = "fix-xwayland-drags",
    match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
    no_focus = true,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

-- Super alone = start menu, like Windows. `release` fires on key-up.
hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("pkill rofi || " .. launcher), { release = true })
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(launcher))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(launcher))

-- Alt+Tab cycles windows on the current workspace.
hl.bind("ALT + TAB", hl.dsp.window.cycle_next())
hl.bind("ALT + SHIFT + TAB", hl.dsp.window.cycle_next({ prev = true }))

hl.bind(mainMod .. " + O", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind("ALT + F4", hl.dsp.window.close())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + Z", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + T", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + SHIFT + X", hl.dsp.exit())

hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu -p 'Clipboard' | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpaper-picker.sh"))

-- Screenshots: PrintScreen = area to clipboard; Shift+Print = area to ~/Pictures
hl.bind("Print", hl.dsp.exec_cmd("grimblast --freeze copy area"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh"))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("grimblast --freeze copy area"))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("~/.config/hypr/scripts/record.sh"))

-- Media keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Focus with Super + arrows
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Move windows with Super + Shift + arrows
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.swap({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.swap({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.swap({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.swap({ direction = "down" }))

-- Workspaces: Super + [1-9,0]; move window with Super + Shift + number
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i, follow = false }))
end
hl.bind("CONTROL + ALT + right", hl.dsp.focus({ workspace = "+1" }))
hl.bind("CONTROL + ALT + left",  hl.dsp.focus({ workspace = "-1" }))

-- Super + scroll cycles workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with Super + left/right mouse drag
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar")
    hl.exec_cmd("dunst")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    -- Restore the last wallpaper (or pick one if none is saved) and theme everything
    hl.exec_cmd("sleep 3 && ~/.config/hypr/scripts/restore-wallpaper.sh")
end)
