-- Hyprland colors — auto-generated by wallust, do not edit manually
-- Required by ~/.config/hypr/hyprland.lua

hl.config({
    general = {
        col = {
            active_border = {
                colors = { "rgb(9D9A93)", "rgb(5E5147)" },
                angle = 45,
            },
            inactive_border = "rgba(38363666)",
        },
    },
})
