# zsh colors — auto-generated by wallust, do not edit manually

typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[command]='fg=#867F75'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#867F75'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#867F75'
ZSH_HIGHLIGHT_STYLES[function]='fg=#867F75'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#867F75,underline'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#53534F'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#9C978E'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#837A6C'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#837A6C'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#837A6C'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#A09A91'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#A09A91'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#9E9B97'
ZSH_HIGHLIGHT_STYLES[path]='fg=#F0EEE9,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#747771'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#F0EEE9'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#9C978E'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#A09A91'

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#9E9B97'
