# zsh colors — auto-generated by wallust, do not edit manually

typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[command]='fg=#72808E'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#72808E'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#72808E'
ZSH_HIGHLIGHT_STYLES[function]='fg=#72808E'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#72808E,underline'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#3D454A'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#7F91A3'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#5A697C'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#5A697C'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#5A697C'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#8999AA'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#8999AA'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#939BA3'
ZSH_HIGHLIGHT_STYLES[path]='fg=#E6EDF5,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#42484F'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#E6EDF5'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#7F91A3'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#8999AA'

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#939BA3'
