# zsh colors — auto-generated by wallust, do not edit manually

typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[command]='fg=#BF9F63'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#BF9F63'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#BF9F63'
ZSH_HIGHLIGHT_STYLES[function]='fg=#BF9F63'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#BF9F63,underline'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#7F9990'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#A1B0A2'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#8AA592'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#8AA592'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#8AA592'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#BFAE55'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#BFAE55'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#ACA57B'
ZSH_HIGHLIGHT_STYLES[path]='fg=#FFF7CD,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#8F94AE'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#FFF7CD'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#A1B0A2'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#BFAE55'

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#ACA57B'
